#pragma once
#include "Shader.h"
#include "TriangleDataBindingWrapper.h"
#include "Texture2DWrapper.h"
#include "FreeMovementCamera.h"
#include "FPSCamera.h"
#include "Mesh.h"
#include "Model.h"
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"